---
- name: Install php and dependencies
  apt:
    name:
      - "php8.3"
      - "php8.3-mysqli"
      - "php8.3-mbstring"
      - "git"
    state: present

- name: Check if web root directory exists
  stat:
    path: "{{ web_root }}"
  register: web_root_stat

- name: Ensure web root directory is empty
  command: rm -rf {{ web_root }}
  when: web_root_stat.stat.exists and web_root_stat.stat.isdir

- name: Clone Git repository if not present
  git:
    repo: "{{ git_repo }}"
    dest: "{{ web_root }}/"
    update: yes

- name: Import SQL file into database
  mysql_db:
    name: "{{ db_name }}"
    state: import
    target: "{{ web_root }}/db.sql"
    login_user: root
    login_password: "{{ mysql_root_password }}"
