---
- name: Intall mysql server and python dependencies
  apt:
    name:
      - "mysql-server"
      - "python3-pymysql"
    state: present

- name: Set mySQL password
  command: mysql -u root -e 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  when: mysql_root_password is defined
  ignore_errors: true

- name: Create blog database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  
- name: Create mySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
